### ISSUE TITLE
Capa

### ISSUE THREAD

**Issue by soaresmat** [soaresmat/Nottus#1]
A capa deve conter:

- [x] Nome do curso
- [x] Componentes da equipe
- [x] Título e subtítulo
- [x] Tipo do projeto
- [x] Ano

**Comment by soaresmat** [comment]
Iniciando o nosso projeto, começando pela documentação do Pré-Projeto para ser entregue no portal no dia 26/02/2018.

OBS: Mostrar para o professor até dia 19/02/2018;

**Comment by RodrigoDavid** [comment]
Já temos a capa? @soaresmat

**Comment by soaresmat** [comment]
O Alexandre fez a capa

**Comment by RodrigoDavid** [comment]
Faz o commit aqui então! @Diedzits

**Comment by Diedzits** [comment]
Tá lá no driver

Em 24 de dez de 2017 4:46 PM, "Rodrigo Reis" <notifications@github.com>
escreveu:

Faz o commit aqui então! @Diedzits <https://github.com/diedzits>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/soaresmat/Nottus/issues/1#issuecomment-353798369>, or mute
the thread

**Comment by soaresmat** [comment]
Anexe a capa para nós Rodrigo @RodrigoDavid

**Comment by emabeghetto** [comment]
estou anexando a capa junto ao pre projeto na outra task
